apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reseau.fullname" . }}-configmap
  labels:
    {{- include "reseau.labels" . | nindent 4 }}
data:
  GMAIL_APP_PASSWORD: "xpic zpwf rvxx jqpt" # for the use of gmail smtp server
{{ printf "environments/configmap.%s.yaml" .Values.environment | .Files.Get | indent 2 }}