{{- if .Values.managedCertificate.enabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.envPrefix }}{{ include "reseau.fullname" . }}-managed-cert
spec:
  domains:
    - {{ .Values.managedCertificate.domain }}
{{- end }}