{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reseau.fullname" . }}-sa
imagePullSecrets:
  - name: {{ .Values.imagePullSecrets }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
