{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reseau.fullname" . }}-sa
  labels:
    {{- include "reseau.labels" . | nindent 4 }}
imagePullSecrets:
  - name: {{ .Values.imagePullSecrets }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
