---
# task file for config_kubernetes

- name: Create a k8s namespace
  kubernetes.core.k8s:
    kubeconfig: ./vars/config
    name: test-namespace
    api_version: v1
    kind: Namespace
    state: present