update interest set name='Entrepreneuriat' where id = 1;
update interest set name='Musculation' where id = 2;
update interest set name='Santé mentale' where id = 3;
insert into interest (name) values ('E-commerce');
insert into interest (name) values ('Trading');
insert into interest (name) values ('CrossFit');
insert into interest (name) values ('Haltérophilie');
insert into interest (name) values ('Immobilier');
insert into interest (name) values ('Philosophie');
insert into interest (name) values ('Course à pied');
insert into interest (name) values ('Création de contenu');
insert into interest (name) values ('Écriture');
insert into interest (name) values ('Crypto');
insert into interest (name) values ('Coaching');
insert into interest (name) values ('Dropshipping');
insert into interest (name) values ('Sport de combat');
insert into interest (name) values ('Voyage');
insert into interest (name) values ('Dev');
insert into interest (name) values ('Vidéo');
