# This workflow deploy the latest Helm Chart to GKE Pre-production when manually triggered or triggered by the provision_infra_preprod pipeline.

name: Deployment to GKE Pre-production

on:
  #[repository_dispatch]
  [workflow_dispatch]
  
env:
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_LOCATION: europe-west1
  GKE_ZONE: europe-west1-b
  REGISTRY: ghcr.io
  IMAGE_NAME: co-bdt/reseau
  TOKEN: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
jobs:
  build-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    environment: pre-production
    permissions:
      contents: 'read'
      packages: 'write'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: preprod

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Update Image Version in the related HelmChart values.yaml
    - name: Update Helm Chart
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'helm/reseau/Chart.yaml'
        token: ${{ env.TOKEN }}
        branch: preprod
        createPR: false
        message: 'Auto Update Helm Chart [skip ci]'
        quotingType: '"'
        changes: |
            {
              "version": "1.0.${{ vars.HELM_CHART_MINOR_VERSION }}",
              "appVersion": "${{ vars.MAJOR_VERSION }}.${{ vars.MINOR_VERSION }}"
            }

    # Build the Docker image and Push it to GHCR
    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: reseau/
        file: reseau/app.Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ vars.MAJOR_VERSION }}.${{ vars.MINOR_VERSION }}
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: pre-production
    permissions:
      contents: 'read'
      packages: 'write'
      id-token: 'write'
    env:
      GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
    needs: [build-publish]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: preprod

    # Authenticate and connect to GCloud and GKE
    - name: GCloud and GKE setup
      uses: ./.github/gcloud-gke-setup
      with:
        WORKLOAD_IDENTITY_PROVIDER_ID: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        PROJECT_ID: ${{ env.PROJECT_ID }}
        GCP_LOCATION: ${{ env.GCP_LOCATION }}
        GKE_CLUSTER_NAME: ${{ env.GKE_CLUSTER_NAME }}

    - name: Package Chart
      run: |-
        cd helm
        helm package reseau

    - name: Deploy Chart
      run: |-
        helm upgrade reseau helm/reseau-*.tgz --install -f environments/values.preprod.yaml --wait #--dry-run
        
    - name: Verify deployment
      run: |-
        helm list

  auto-increment-version:
    name: Auto Increment Version
    runs-on: ubuntu-latest
    environment: pre-production
    permissions:
      contents: 'read'
      packages: 'write'
      id-token: 'write'
    needs: [deploy]

    steps:
    # Increment the Image Minor Version variable
    - name: Increment Minor Version
      uses: action-pack/increment@v2
      with:
        name: 'MINOR_VERSION'
        repository: ${{ github.repository }}
        token: ${{ env.TOKEN }}

    # Increment the Helm Chart Minor Version variable
    - name: Increment Minor Version
      uses: action-pack/increment@v2
      with:
        name: 'HELM_CHART_MINOR_VERSION'
        repository: ${{ github.repository }}
        token: ${{ env.TOKEN }}
