# This workflow will build a docker container, publish it to GitHub Container Registry, and deploy it to GKE when there is a push to the "main" branch.

name: Build, Publish and Deploy to GKE

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_LOCATION: europe-west1
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: europe-west1-b
  REGISTRY: ghcr.io
  IMAGE_NAME: co-bdt/reseau
  TOKEN: ${{ secrets.ACTIONS_ACCESS_TOKEN }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      packages: 'write'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Increment the Image Minor Version variable
    - name: Increment Minor Version
      uses: action-pack/increment@v2
      with:
        name: 'MINOR_VERSION'
        repository: ${{ github.repository }}
        token: ${{ env.TOKEN }}

    # Increment the Helm Chart Minor Version variable
    - name: Increment Minor Version
      uses: action-pack/increment@v2
      with:
        name: 'HELM_CHART_MINOR_VERSION'
        repository: ${{ github.repository }}
        token: ${{ env.TOKEN }}

    # Update Image Version in the related HelmChart values.yaml
    - name: Update Helm Chart
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'helm/reseau/Chart.yaml'
        token: ${{ env.TOKEN }}
        branch: main
        createPR: false
        message: 'Auto Update Helm Chart [skip ci]'
        quotingType: '"'
        changes: |
            {
              "version": "1.0.${{ vars.HELM_CHART_MINOR_VERSION }}",
              "appVersion": "${{ vars.MAJOR_VERSION }}.${{ vars.MINOR_VERSION }}"
            }

    # Build the Docker image and Push it to GHCR
    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: reseau/
        file: reseau/app.Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ vars.MAJOR_VERSION }}.${{ vars.MINOR_VERSION }}

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/758161621186/locations/global/workloadIdentityPools/github-actions/providers/reseau-gh-repo'

    # Required for downloading GKE Cloud auth plugin
    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    # This plugin seems to be necessary in order to use Kubernetes API and therefore, Helm
    - name: Setup GKE GCloud Auth plugin
      run: |-
        gcloud components install gke-gcloud-auth-plugin
        gke-gcloud-auth-plugin --version

    # Get the GKE credentials so we can deploy to the cluster
    - name: Get cluster credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER_NAME }}
        location: ${{ env.GCP_LOCATION }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Package Chart
      run: |-
        cd helm
        helm package reseau

    - name: Deploy Chart
      run: |-
        helm upgrade reseau helm/reseau-*.tgz --wait #--dry-run
        
    - name: Verify deployment
      run: |-
        helm list
