# This workflow will deploy the latest Reseau image from GHCR to GKE Production when there is a push to the "main" branch.

name: Deploy to GKE Prod

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]

env:
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_LOCATION: europe-west1
  GKE_ZONE: europe-west1-b

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      packages: 'write'
      id-token: 'write'
    env:
      GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    # Authenticate and connect to GCloud and GKE
    - name: GCloud and GKE setup
      uses: ./.github/gcloud-gke-setup
      with:
        WORKLOAD_IDENTITY_PROVIDER_ID: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        PROJECT_ID: ${{ env.PROJECT_ID }}
        GCP_LOCATION: ${{ env.GCP_LOCATION }}
        GKE_CLUSTER_NAME: ${{ env.GKE_CLUSTER_NAME }}

    - name: Package Chart
      run: |-
        cd helm
        helm package reseau

    - name: Deploy Chart
      run: |-
        helm upgrade reseau helm/reseau-*.tgz --install -f helm/reseau/environments/values.prod.yaml --wait --timeout 10m0s
