# This workflow will provision the project infrastructure by running Terraform and configure the cluster

name: Provision Infra

on:
  [workflow_dispatch]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_LOCATION: europe-west1
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: europe-west1-b
  REGISTRY: ghcr.io
  TOKEN: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
  TERRAFORM_VERSION: 1.9.2

jobs:
  run-terraform:
    name: Run Terraform
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      packages: 'write'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "${{ env.TERRAFORM_VERSION }}"

    - name: Plan changes
      working-directory: terraform/prod/
      run: |-
        terraform version
        ls -la
    
    #- run: echo ${{ steps.plan.outputs.stdout }}

  configuration:
    name: Configuration
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      packages: 'write'
      id-token: 'write'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/758161621186/locations/global/workloadIdentityPools/github-actions/providers/reseau-gh-repo'

    # Required for downloading GKE Cloud auth plugin
    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    # This plugin seems to be necessary in order to use Kubernetes API and therefore, Helm
    - name: Setup GKE GCloud Auth plugin
      run: |-
        gcloud components install gke-gcloud-auth-plugin
        gke-gcloud-auth-plugin --version

    # Get the GKE credentials so we can setup the cluster
    - name: Get cluster credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER_NAME }}
        location: ${{ env.GCP_LOCATION }}
        project_id: ${{ env.PROJECT_ID }}

    # Create the Secret for pulling images with Docker config file
    - name: Create Docker config Secret
      run: |-
        kubectl create secret docker-registry reseau-dockerconfig-secret \
          --from-file=.dockerconfigjson=/home/$USER/.docker/config.json
