# This workflow will provision the project infrastructure by running Terraform and configure the cluster

name: Provision Infrastructure

on:
  [workflow_dispatch]

env:
  GCP_ID_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_LOCATION: europe-west1
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: europe-west1-b
  AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}
  AWS_LOCATION: eu-west-3
  AWS_RDS_PWD: ${{ secrets.AWS_RDS_INSTANCE_PASSWORD }}
  REGISTRY: ghcr.io
  TOKEN: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
  TERRAFORM_VERSION: 1.9.2

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'  # This is required for actions/checkout
      id-token: 'write' # This is required for requesting the JWT

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    # Configure Workload Identity Federation and generate an access token.
    - name: Configure GCP Credentials
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ env.GCP_ID_PROVIDER }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_IAM_ROLE }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_LOCATION }}

    # Install and setup Terraform
    #- name: Setup Terraform
    #  uses: hashicorp/setup-terraform@v3
    #  with:
    #    terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Terraform Init
      working-directory: terraform/prod/
      run: |-
        terraform init

    # Plan changes to be applied by Terraform
    - name: Plan changes
      working-directory: terraform/prod/
      run: |-
        terraform plan -out tfplan -var project_id=$PROJECT_ID -var aws_rds_password=$AWS_RDS_PWD

    # Save plan to GH Artifacts to retrieve it in the next job
    - name: Save Artifact
      id: save-artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.run_id }}-tfplan
        path: terraform/prod/tfplan
        retention-days: 1

  terraform-apply:
      name: Terraform Apply
      runs-on: ubuntu-latest
      environment: production
      permissions:
        contents: 'read'
        id-token: 'write'
      needs: [terraform-plan]
  
      steps:
      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ env.TOKEN }}
          approvers: Co-Bdt
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.run_id }}-tfplan
          path: terraform/prod/
          github_token: ${{ env.TOKEN }}

      # Configure Workload Identity Federation and generate an access token.
      - name: Configure GCP Credentials
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ env.GCP_ID_PROVIDER }}
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_IAM_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_LOCATION }}

      - name: Terraform Init
        working-directory: terraform/prod/
        run: |-
          terraform init
  
      - name: Apply changes
        working-directory: terraform/prod/
        run: |-
          terraform apply tfplan

  configuration:
    name: Configuration
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'
    needs: [terraform-apply]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ env.TOKEN }}

    # Authenticate and connect to GCloud and GKE
    - name: GCloud and GKE setup
      uses: ./.github/gcloud-gke-setup
      with:
        WORKLOAD_IDENTITY_PROVIDER_ID: ${{ env.GCP_ID_PROVIDER }}
        PROJECT_ID: ${{ env.PROJECT_ID }}
        GCP_LOCATION: ${{ env.GCP_LOCATION }}
        GKE_CLUSTER_NAME: ${{ env.GKE_CLUSTER_NAME }}

    # Create the Secret for pulling images with Docker config file
    - name: Create Docker config Secret
      run: |-
        kubectl create secret docker-registry reseau-dockerconfig-secret \
          --from-file=.dockerconfigjson=/home/$USER/.docker/config.json

  call_deploy_workflow:
    name: Call Deploy Workflow
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'
    needs: [configuration]

    steps:
    - name: Deploy
      run: |-
        curl -X POST https://api.github.com/repos/Co-Bdt/Reseau/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -u $TOKEN }} \
        --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'

    - name: Checkout
      uses: actions/checkout@v3
