# This workflow will provision the project infrastructure by running Terraform and configure the cluster

name: Provision Infra

on:
  [workflow_dispatch]

env:
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_LOCATION: europe-west1
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: europe-west1-b
  REGISTRY: ghcr.io
  TOKEN: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
  TERRAFORM_VERSION: 1.9.2

jobs:
  run-terraform:
    name: Run Terraform
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      packages: 'write'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "${{ env.TERRAFORM_VERSION }}"

    - name: Plan changes
      working-directory: terraform/prod/
      run: |-
        terraform version
        ls -la
    
    #- run: echo ${{ steps.plan.outputs.stdout }}

  configuration:
    name: Configuration
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      packages: 'write'
      id-token: 'write'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Authenticate and connect to GCloud and GKE
    - name: GCloud and GKE setup
      uses: ./.github/gcloud-gke-setup
      with:
        WORKLOAD_IDENTITY_PROVIDER_ID: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        PROJECT_ID: ${{ env.PROJECT_ID }}
        GCP_LOCATION: ${{ env.GCP_LOCATION }}
        GKE_CLUSTER_NAME: ${{ env.GKE_CLUSTER_NAME }}

    # Create the Secret for pulling images with Docker config file
    - name: Create Docker config Secret
      run: |-
        kubectl create secret docker-registry reseau-dockerconfig-secret \
          --from-file=.dockerconfigjson=/home/$USER/.docker/config.json
