# This workflow deploy the latest Helm Chart to GKE when manually triggered.

name: Manual Deployment to GKE

on:
  [repository_dispatch]
  #[workflow_dispatch]
  
env:
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_LOCATION: europe-west1
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: europe-west1-b
  REGISTRY: ghcr.io
  IMAGE_NAME: co-bdt/reseau
  TOKEN: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      packages: 'write'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    # Authenticate and connect to GCloud and GKE
    - name: GCloud and GKE setup
      uses: ./.github/gcloud-gke-setup
      with:
        WORKLOAD_IDENTITY_PROVIDER_ID: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        PROJECT_ID: ${{ env.PROJECT_ID }}
        GCP_LOCATION: ${{ env.GCP_LOCATION }}
        GKE_CLUSTER_NAME: ${{ env.GKE_CLUSTER_NAME }}

    - name: Package Chart
      run: |-
        cd helm
        helm package reseau

    - name: Deploy Chart
      run: |-
        helm install reseau helm/reseau-*.tgz --wait #--dry-run
        
    - name: Verify deployment
      run: |-
        helm list
